# k2 apply -f examples/demo/a/step1-in-cluster-2.yaml

# k2 delete -f examples/demo/a/step1-in-cluster-2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels:
    app: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:

    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: public.ecr.aws/x2j8p8w7/http-server:latest
        env:
        - name: PodName
          value: "service-2 pod from cluster 2"
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: service2
  annotations:
    multicluster.x-k8s.io/federation: "amazon-vpc-lattice"

