# k1 apply -f examples/demo/b/step2-in-cluster-1.yaml
# another terminal:
# alias k1='kubectl --context arn:aws:eks:us-west-2:348739612106:cluster/cluster-1'
# export LATTICE_SERVICE_DNS=$(k1 get httproute my-httproute -o json | jq -r '.metadata.annotations["application-networking.k8s.aws/lattice-assigned-domain-name"]') && echo $LATTICE_SERVICE_DNS
#  while true; do k1 exec client -- curl $LATTICE_SERVICE_DNS 2>/dev/null; sleep 1; done

# k1 delete -f examples/demo/b/step2-in-cluster-1.yaml


apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-httproute
spec:
  parentRefs:
    - name: my-gateway
      sectionName: http
  rules:
    - backendRefs:
        - name: service1-v1
          kind: ServiceImport
          weight: 50
        - name: service1-v2
          kind: ServiceImport
          weight: 50


---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: service1-v2
spec:
  type: ClusterSetIP
  ports:
    - port: 80
      protocol: TCP